import { Test } from '@nestjs/testing';
import { ImageOptimizerService, DEFAULT_IMAGE_VARIANTS } from './image-optimizer.service';

describe('ImageOptimizerService', () => {
  let service: ImageOptimizerService;

  beforeEach(async () => {
    const module = await Test.createTestingModule({
      providers: [ImageOptimizerService],
    }).compile();
    service = module.get<ImageOptimizerService>(ImageOptimizerService);
  });

  it('detects images by mimetype', () => {
    expect(service.isImage('image/jpeg')).toBe(true);
    expect(service.isImage('image/png')).toBe(true);
    expect(service.isImage('application/pdf')).toBe(false);
  });

  it('returns null for non-image buffers', async () => {
    const result = await service.optimize(Buffer.from('not-an-image'), 'application/pdf');
    expect(result).toBeNull();
  });

  it('produces WebP original + responsive variants', async () => {
    // 10x10 solid red PNG (valid, generated by sharp)
    const png = Buffer.from(
      'iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAFElEQVQYlWP4z8CABzGMSjNgCQMAt8pjnanKDKUAAAAASUVORK5CYII=',
      'base64',
    );
    const result = await service.optimize(png, 'image/png');
    expect(result).not.toBeNull();
    expect(result!.format).toBe('webp');
    expect(result!.variants).toHaveProperty('thumb');
    expect(result!.variants).toHaveProperty('medium');
    expect(result!.variants).toHaveProperty('large');
    expect(result!.original.length).toBeGreaterThan(0);
  });

  it('falls back to null on corrupt image', async () => {
    const result = await service.optimize(Buffer.from('garbage'), 'image/jpeg');
    expect(result).toBeNull();
  });

  it('exposes default variant specs', () => {
    expect(DEFAULT_IMAGE_VARIANTS).toHaveLength(3);
  });
});