import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Baseline schema for all 40 entities, generated from entity metadata against
 * an empty database, then hand-adjusted.
 *
 * Hand adjustments:
 *  - CREATE EXTENSION IF NOT EXISTS "uuid-ossp" (required by uuid_generate_v4()).
 *  - Known cosmetic schema:log drift: 4 fractional decimal defaults
 *    (fee_configs.vatPct, llm_models.defaultTemperature,
 *    ai_feature_configs.temperature, agent_instances.temperature) show as
 *    pending SET DEFAULT because TypeORM's Postgres driver re-quotes only
 *    integer defaults when reading them back. Harmless — columns, types and
 *    defaults are correct, and production runs with synchronize=false.
 */
export class Baseline1788166706152 implements MigrationInterface {
    name = 'Baseline1788166706152'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "balance" numeric(18,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "hasPin" boolean NOT NULL DEFAULT false, "pinHash" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('deposit', 'withdraw', 'escrow_release', 'escrow_refund')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_status_enum" AS ENUM('completed', 'pending', 'failed')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(18,2) NOT NULL, "status" "public"."wallet_transactions_status_enum" NOT NULL DEFAULT 'completed', "reference" character varying, "description" character varying, "balanceAfter" numeric(18,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4b3d5cb7b4480ca1c3c367ebb4" ON "wallet_transactions" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a94d9d61a2b05123710b325fb" ON "wallet_transactions" ("walletId") `);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('open', 'in_progress', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject" character varying NOT NULL, "description" text, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'open', "userId" character varying NOT NULL, "userName" character varying, "userEmail" character varying, "messages" jsonb NOT NULL DEFAULT '[]', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_subscriptions_status_enum" AS ENUM('pending', 'confirmed', 'unsubscribed')`);
        await queryRunner.query(`CREATE TABLE "email_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "token" character varying(64) NOT NULL, "status" "public"."email_subscriptions_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8e8eebc384627fb6fa7fd3993fd" UNIQUE ("email"), CONSTRAINT "PK_e60e3a09d341892b331d0e14e98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8e8eebc384627fb6fa7fd3993f" ON "email_subscriptions" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('bid_outbid', 'auction_won', 'auction_ended', 'invite_approved', 'room_started', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "body" text, "link" character varying(500), "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('issued', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_number" character varying(50) NOT NULL, "auction_id" uuid NOT NULL, "product_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "seller_id" uuid NOT NULL, "hammer_price" numeric(18,2) NOT NULL DEFAULT '0', "commission" numeric(18,2) NOT NULL DEFAULT '0', "vat" numeric(18,2) NOT NULL DEFAULT '0', "fixed_fee" numeric(18,2) NOT NULL DEFAULT '0', "total" numeric(18,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'issued', "issued_at" TIMESTAMP NOT NULL DEFAULT now(), "paid_at" TIMESTAMP, "payment_method" character varying(50), "payment_reference" character varying(255), "payment_status_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8506594bec20d9388d86bdf9c0" ON "invoices" ("payment_reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e0c335d17e13b29ffabb74fa7" ON "invoices" ("auction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_44bb811de7d3cef32f28094ea1" ON "invoices" ("seller_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8efb05dbd2ceb9ab8e37c446d1" ON "invoices" ("buyer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE TYPE "public"."invites_expiry_enum" AS ENUM('1h', '24h', '7d', 'never')`);
        await queryRunner.query(`CREATE TYPE "public"."invites_mode_enum" AS ENUM('exclusive', 'request')`);
        await queryRunner.query(`CREATE TYPE "public"."invites_response_enum" AS ENUM('pending', 'accepted', 'declined')`);
        await queryRunner.query(`CREATE TABLE "invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" character varying NOT NULL, "roomId" character varying NOT NULL, "token" character varying NOT NULL, "createdBy" character varying NOT NULL, "expiry" "public"."invites_expiry_enum" NOT NULL DEFAULT '24h', "expiresAt" TIMESTAMP NOT NULL, "usageCount" integer NOT NULL DEFAULT '0', "maxUsage" integer NOT NULL DEFAULT '10', "isActive" boolean NOT NULL DEFAULT true, "mode" "public"."invites_mode_enum" NOT NULL DEFAULT 'exclusive', "response" "public"."invites_response_enum" NOT NULL DEFAULT 'pending', "inviteeEmail" character varying, "inviteeName" character varying, "respondedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa52e96b44a714372f4dd31a0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fee_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying NOT NULL DEFAULT 'default', "displayName" character varying(255) NOT NULL DEFAULT 'Platform Default', "commissionPct" numeric(5,2) NOT NULL DEFAULT '10', "vatPct" numeric(5,2) NOT NULL DEFAULT '7.5', "otherChargesPct" numeric(5,2) NOT NULL DEFAULT '0', "fixedFee" numeric(18,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9353f3fc4bd5b35c9615f77a2ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a09e22b97a449f71089f32cfd" ON "fee_configs" ("category") `);
        await queryRunner.query(`CREATE TABLE "faqs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category" character varying NOT NULL, "question" character varying NOT NULL, "answer" text NOT NULL, "order" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2ddf4f2c910f8e8fa2663a67bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exchange_rates" ("code" character varying(3) NOT NULL, "rate" numeric(18,6) NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0c04fc0f09c2b8c99980d979b47" PRIMARY KEY ("code"))`);
        await queryRunner.query(`CREATE TABLE "banners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "imageUrl" character varying NOT NULL, "link" character varying, "position" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "type" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9b186b959296fcb940790d31c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "content_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "metaDescription" character varying, "metaTitle" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cc23a46df001843d70d6c3c650c" UNIQUE ("slug"), CONSTRAINT "PK_5f7201667a2be0ed2f8f9a0876d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_reason_enum" AS ENUM('not_as_described', 'non_delivery', 'payment_issue', 'conduct', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."disputes_status_enum" AS ENUM('open', 'under_review', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "disputes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "openedById" uuid NOT NULL, "againstUserId" uuid, "productId" uuid, "invoiceId" uuid, "reason" "public"."disputes_reason_enum" NOT NULL, "description" text NOT NULL, "status" "public"."disputes_status_enum" NOT NULL DEFAULT 'open', "resolution" text, "resolvedById" uuid, "resolvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c97580d01c1a4b0b345c42a107" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4decac99e117c3d35e57f2c1fc" ON "disputes" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ea46f4f2225f38d127063c367" ON "disputes" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cf9289f2af9e6714ded345d513" ON "disputes" ("openedById") `);
        await queryRunner.query(`CREATE TABLE "dispute_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "disputeId" uuid NOT NULL, "userId" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3e26776618f5bbe7316336133e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b266f01ca1d077e7ff24c7f67a" ON "dispute_feedback" ("disputeId", "userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5dc503fab3480182bf436685c" ON "dispute_feedback" ("disputeId") `);
        await queryRunner.query(`CREATE TYPE "public"."condition_reports_condition_enum" AS ENUM('new', 'like_new', 'used', 'refurbished', 'damaged', 'not_tested')`);
        await queryRunner.query(`CREATE TYPE "public"."condition_reports_grade_enum" AS ENUM('A', 'B', 'C', 'D', 'E')`);
        await queryRunner.query(`CREATE TABLE "condition_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "condition" "public"."condition_reports_condition_enum" NOT NULL, "grade" "public"."condition_reports_grade_enum" NOT NULL, "summary" text NOT NULL, "defects" jsonb NOT NULL DEFAULT '[]', "inspectedAtLocation" character varying(255), "reportedById" uuid, "reporterName" character varying(120), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eabcd4ec9f91b83aa6b24dbc0ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68c7053f31a2c7f96957097320" ON "condition_reports" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_afd0ea7f2d5c017432412f0f29" ON "condition_reports" ("productId") `);
        await queryRunner.query(`CREATE TABLE "shipping_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "label" character varying(40) NOT NULL DEFAULT 'Home', "recipientName" character varying(120) NOT NULL, "phone" character varying(30) NOT NULL, "line1" character varying(255) NOT NULL, "line2" character varying(255), "city" character varying(100) NOT NULL, "state" character varying(100), "country" character varying(100) NOT NULL DEFAULT 'Nigeria', "postalCode" character varying(20), "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cced78984eddbbe24470f226692" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f522735551c716dc489635b5b" ON "shipping_addresses" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."sellers_business_type_enum" AS ENUM('INDIVIDUAL', 'SOLE_PROPRIETORSHIP', 'LLC', 'CORPORATION', 'PARTNERSHIP', 'AGENCY', 'GOVERNMENT', 'EMBASSY', 'NGO')`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_auction_visibility_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_verification_status_enum" AS ENUM('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_payout_method_enum" AS ENUM('BANK_TRANSFER', 'MOBILE_MONEY', 'CRYPTO', 'CHECK')`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED')`);
        await queryRunner.query(`CREATE TABLE "sellers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "business_name" character varying(255) NOT NULL, "business_type" "public"."sellers_business_type_enum" NOT NULL DEFAULT 'INDIVIDUAL', "business_registration_number" character varying(100), "tax_id" character varying(100), "business_description" text, "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "website" character varying(255), "contact_person" character varying(255), "contact_person_title" character varying(255), "contact_person_email" character varying(100), "contact_person_phone" character varying(30), "secondary_contact_name" character varying(255), "secondary_contact_title" character varying(255), "secondary_contact_email" character varying(100), "secondary_contact_phone" character varying(30), "auction_visibility" "public"."sellers_auction_visibility_enum" NOT NULL DEFAULT 'public', "consultant_listing" boolean NOT NULL DEFAULT false, "consultant_notes" text, "address_line1" character varying(255) NOT NULL, "address_line2" character varying(255), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postal_code" character varying(20) NOT NULL, "country" character varying(2) NOT NULL DEFAULT 'NG', "verification_status" "public"."sellers_verification_status_enum" NOT NULL DEFAULT 'PENDING', "verification_notes" text, "verified_at" TIMESTAMP, "verified_by_id" uuid, "rejected_at" TIMESTAMP, "rejection_reason" text, "commission_rate" numeric(5,2) NOT NULL DEFAULT '10', "payout_method" "public"."sellers_payout_method_enum", "bank_account_details" jsonb, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "total_sales" numeric(15,2) NOT NULL DEFAULT '0', "total_products" integer NOT NULL DEFAULT '0', "active_products" integer NOT NULL DEFAULT '0', "total_orders" integer NOT NULL DEFAULT '0', "completed_orders" integer NOT NULL DEFAULT '0', "rating" numeric(3,2) NOT NULL DEFAULT '0', "total_reviews" integer NOT NULL DEFAULT '0', "status" "public"."sellers_status_enum" NOT NULL DEFAULT 'INACTIVE', "suspension_reason" text, "suspended_at" TIMESTAMP, "suspended_by_id" uuid, "notifications_enabled" boolean NOT NULL DEFAULT true, "auto_accept_orders" boolean NOT NULL DEFAULT false, "invoice_payment_due_days" integer NOT NULL DEFAULT '7', "require_minimum_bid_deposit" boolean NOT NULL DEFAULT false, "minimum_bid_deposit" numeric(15,2), "business_hours" jsonb, "metadata" jsonb, "internal_notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_83f4670f0e114d0be3731bade87" UNIQUE ("user_id"), CONSTRAINT "UQ_60a049dd3231ed458dccfdaf406" UNIQUE ("email"), CONSTRAINT "PK_97337ccbf692c58e6c7682de8a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0114dd18eecf7423de5c079b04" ON "sellers" ("business_registration_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_b99cb17a41a10ffa3d4d0481d7" ON "sellers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_073d5e6499b5a24cd876f7c7d7" ON "sellers" ("verification_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_83f4670f0e114d0be3731bade8" ON "sellers" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_60a049dd3231ed458dccfdaf40" ON "sellers" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."shipments_method_enum" AS ENUM('pickup', 'delivery')`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('pending', 'dispatched', 'in_transit', 'delivered', 'returned', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "addressId" uuid, "method" "public"."shipments_method_enum" NOT NULL DEFAULT 'delivery', "carrier" character varying(60), "cost" numeric(18,2) NOT NULL DEFAULT '0', "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'pending', "trackingNumber" character varying(80), "estimatedDeliveryAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a19baf6dd62cac42fbb40a518" ON "shipments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c936a07d35e828e7248623242a" ON "shipments" ("invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_statistics_period_type_enum" AS ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TABLE "seller_statistics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "period_type" "public"."seller_statistics_period_type_enum" NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "total_sales" numeric(15,2) NOT NULL DEFAULT '0', "gross_revenue" numeric(15,2) NOT NULL DEFAULT '0', "commission_paid" numeric(15,2) NOT NULL DEFAULT '0', "net_revenue" numeric(15,2) NOT NULL DEFAULT '0', "total_orders" integer NOT NULL DEFAULT '0', "completed_orders" integer NOT NULL DEFAULT '0', "cancelled_orders" integer NOT NULL DEFAULT '0', "refunded_orders" integer NOT NULL DEFAULT '0', "products_listed" integer NOT NULL DEFAULT '0', "products_sold" integer NOT NULL DEFAULT '0', "total_views" integer NOT NULL DEFAULT '0', "total_clicks" integer NOT NULL DEFAULT '0', "unique_customers" integer NOT NULL DEFAULT '0', "repeat_customers" integer NOT NULL DEFAULT '0', "new_customers" integer NOT NULL DEFAULT '0', "reviews_received" integer NOT NULL DEFAULT '0', "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "positive_reviews" integer NOT NULL DEFAULT '0', "negative_reviews" integer NOT NULL DEFAULT '0', "conversion_rate" numeric(5,2) NOT NULL DEFAULT '0', "average_order_value" numeric(15,2) NOT NULL DEFAULT '0', "completion_rate" numeric(5,2) NOT NULL DEFAULT '0', "cancellation_rate" numeric(5,2) NOT NULL DEFAULT '0', "average_response_time_minutes" numeric(10,2) NOT NULL DEFAULT '0', "payouts_requested" integer NOT NULL DEFAULT '0', "payouts_completed" integer NOT NULL DEFAULT '0', "total_payouts" numeric(15,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "calculated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ea4c923cc4a55e0a0919c123a3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_26466f0d02b49c72242fb490db" ON "seller_statistics" ("seller_id", "period_type", "period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_d23c88ea30e4525411813eb90c" ON "seller_statistics" ("period_end") `);
        await queryRunner.query(`CREATE INDEX "IDX_87741141abf4b31b06b7f15f7c" ON "seller_statistics" ("period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_f78e8d7896f293e9f081811f40" ON "seller_statistics" ("period_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_e27e0058b3d3628b12aad5cbde" ON "seller_statistics" ("seller_id") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_reviews_status_enum" AS ENUM('ACTIVE', 'HIDDEN', 'FLAGGED', 'REMOVED')`);
        await queryRunner.query(`CREATE TABLE "seller_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "bidder_id" uuid NOT NULL, "auction_id" uuid, "product_id" uuid, "rating" integer NOT NULL, "comment" text NOT NULL, "title" character varying(100), "communication_rating" integer, "product_quality_rating" integer, "shipping_speed_rating" integer, "packaging_rating" integer, "response" text, "responded_at" TIMESTAMP, "status" "public"."seller_reviews_status_enum" NOT NULL DEFAULT 'ACTIVE', "flag_reason" text, "flagged_by_id" uuid, "flagged_at" TIMESTAMP, "is_verified_purchase" boolean NOT NULL DEFAULT false, "helpful_count" integer NOT NULL DEFAULT '0', "not_helpful_count" integer NOT NULL DEFAULT '0', "images" jsonb, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_70c6a865338101c515c6f13a9ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c9feefbe3bab5ddafe2c685fc5" ON "seller_reviews" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7a1090232cea58e1d2cbc22f7" ON "seller_reviews" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d6ba0d5ed0edd86295d962d8" ON "seller_reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "IDX_961760d26e5cccaaa753d6daaa" ON "seller_reviews" ("auction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a327b87e879deeadf064c2ce99" ON "seller_reviews" ("bidder_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1160ad4ed6fefbc03da0d96f4d" ON "seller_reviews" ("seller_id") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_payouts_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "seller_payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "gross_amount" numeric(15,2) NOT NULL, "commission_amount" numeric(15,2) NOT NULL, "net_amount" numeric(15,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "commission_rate" numeric(5,2) NOT NULL, "status" "public"."seller_payouts_status_enum" NOT NULL DEFAULT 'PENDING', "payout_method" character varying(50) NOT NULL, "payout_details" jsonb NOT NULL, "reference_number" character varying(100) NOT NULL, "transaction_id" character varying(255), "period_start" date, "period_end" date, "orders_count" integer NOT NULL DEFAULT '0', "processed_by_id" uuid, "processing_notes" text, "failure_reason" text, "retry_count" integer NOT NULL DEFAULT '0', "requested_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "approved_at" TIMESTAMP WITH TIME ZONE, "processing_started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "failed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "metadata" jsonb, CONSTRAINT "UQ_d33a9646fe5fffbd65055a47a7b" UNIQUE ("reference_number"), CONSTRAINT "PK_573b32dc5cc1106acd0eb346078" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e683c4b40a92ebcf90e894f599" ON "seller_payouts" ("completed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4faef7f35507187503a365f9fc" ON "seller_payouts" ("requested_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d33a9646fe5fffbd65055a47a7" ON "seller_payouts" ("reference_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e60c9e914a268fefc1d40edd2" ON "seller_payouts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1004f82be695e7a05ff0a724ae" ON "seller_payouts" ("seller_id") `);
        await queryRunner.query(`CREATE TYPE "public"."seller_documents_document_type_enum" AS ENUM('BUSINESS_LICENSE', 'TAX_CERTIFICATE', 'ID_CARD', 'PASSPORT', 'PROOF_OF_ADDRESS', 'BANK_STATEMENT', 'CERTIFICATE_OF_INCORPORATION', 'MEMORANDUM_OF_ASSOCIATION', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."seller_documents_verification_status_enum" AS ENUM('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "seller_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seller_id" uuid NOT NULL, "document_type" "public"."seller_documents_document_type_enum" NOT NULL, "document_number" character varying(255), "description" text, "file_url" character varying(500) NOT NULL, "file_name" character varying(255) NOT NULL, "file_size" integer NOT NULL, "mime_type" character varying(100) NOT NULL, "file_hash" character varying(64), "verification_status" "public"."seller_documents_verification_status_enum" NOT NULL DEFAULT 'PENDING', "verification_notes" text, "verified_at" TIMESTAMP, "verified_by_id" uuid, "rejection_reason" text, "issue_date" date, "expires_at" date, "metadata" jsonb, "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_21b439eb3e12ca544b8031c8423" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_711765a507b3e11353745309a8" ON "seller_documents" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0822da92cfab6049571426539b" ON "seller_documents" ("verification_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_0275e551cf97a66c7fc9df2ac1" ON "seller_documents" ("document_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4e613c1ed4b182686976022f1" ON "seller_documents" ("seller_id") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('bidder', 'seller', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'bidder', "name" character varying NOT NULL, "isEmailVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "clerkId" character varying, "otpCode" character varying(6), "otpExpiry" TIMESTAMP, "phone" character varying(30), "address" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_type_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_status_enum" AS ENUM('scheduled', 'live', 'closed', 'cancelled', 'settled')`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "roomCode" character varying NOT NULL, "type" "public"."rooms_type_enum" NOT NULL DEFAULT 'public', "requiresDeposit" boolean NOT NULL DEFAULT false, "depositAmount" numeric(18,2), "requiresBidFee" boolean NOT NULL DEFAULT false, "bidFeeAmount" numeric(18,2), "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP NOT NULL, "duration" character varying NOT NULL DEFAULT '7 days', "status" "public"."rooms_status_enum" NOT NULL DEFAULT 'scheduled', "allowInviteCode" boolean NOT NULL DEFAULT false, "inviteCode" character varying, "invitedUserIds" text NOT NULL DEFAULT '', "createdById" uuid NOT NULL, "productIds" text NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_218122bdbe19989effd16195807" UNIQUE ("roomCode"), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roomId" uuid NOT NULL, "userId" uuid NOT NULL, "hasPaidDeposit" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT false, "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_58f6bdfdb92476fdd5525655431" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_reservepricevisibility_enum" AS ENUM('hidden', 'exposed')`);
        await queryRunner.query(`CREATE TYPE "public"."products_auctiontype_enum" AS ENUM('direct_sale', 'open_auction', 'exclusive_auction')`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'rejected', 'active', 'sold', 'expired', 'closed', 'withdrawn')`);
        await queryRunner.query(`CREATE TYPE "public"."products_visibility_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "slug" character varying, "description" text, "city" character varying, "country" character varying, "countryCode" character varying, "lotNumber" character varying, "startingBid" numeric(18,2) NOT NULL, "currentBid" numeric(18,2) NOT NULL DEFAULT '0', "category" character varying NOT NULL, "subCategory" character varying, "tags" text, "specifications" jsonb, "images" jsonb, "endTime" TIMESTAMP NOT NULL, "totalBids" integer NOT NULL DEFAULT '0', "reservePrice" numeric(18,2), "buyNowPrice" numeric(18,2), "hasReservePrice" boolean NOT NULL DEFAULT false, "reservePriceVisibility" "public"."products_reservepricevisibility_enum" NOT NULL DEFAULT 'hidden', "allowBuyNow" boolean NOT NULL DEFAULT false, "auctionDuration" character varying NOT NULL DEFAULT '7 days', "auctionType" "public"."products_auctiontype_enum" NOT NULL DEFAULT 'open_auction', "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft', "visibility" "public"."products_visibility_enum" NOT NULL DEFAULT 'public', "sellerId" uuid NOT NULL, "approvedBy" character varying, "approvedAt" TIMESTAMP, "rejectionReason" character varying, "version" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c3932231d2385ac248d0888d95" ON "products" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_af69252f6f711708061c2d67f9" ON "products" ("status", "endTime") `);
        await queryRunner.query(`CREATE INDEX "IDX_e40a1dd2909378f0da1f34f7bd" ON "products" ("sellerId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_type_enum" AS ENUM('invoice', 'deposit')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('paystack', 'flutterwave', 'interswitch', 'opay')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'succeeded', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "invoiceId" uuid, "type" "public"."payments_type_enum" NOT NULL, "provider" "public"."payments_provider_enum" NOT NULL, "reference" character varying(255) NOT NULL, "providerReference" character varying(255), "amount" numeric(18,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d07ab3951e510598b2a33290b" ON "payments" ("provider", "providerReference") `);
        await queryRunner.query(`CREATE INDEX "IDX_43d19956aeab008b49e0804c14" ON "payments" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d35cb3c13a18e1ea1705b2817b" ON "payments" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_866ddee0e17d9385b4e3b86851" ON "payments" ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_holds_status_enum" AS ENUM('held', 'disputed', 'released', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "escrow_holds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "buyerId" uuid NOT NULL, "sellerId" uuid NOT NULL, "status" "public"."escrow_holds_status_enum" NOT NULL DEFAULT 'held', "refundReason" text, "resolvedById" uuid, "releasedAt" TIMESTAMP, "refundedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7c254076b2a5b3ee9b8c4a1f8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a81c6970787322a7763800ffe1" ON "escrow_holds" ("sellerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86e3711405e44c3cb75fbe4c32" ON "escrow_holds" ("buyerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77879ae87bfd6ec2b09f1aef64" ON "escrow_holds" ("invoiceId") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "imageUrl" character varying, "subCategories" text, "productCount" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bids" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "roomId" uuid, "bidderId" uuid NOT NULL, "amount" numeric(18,2) NOT NULL, "maxBid" numeric(18,2), "isAutoBid" boolean NOT NULL DEFAULT false, "isWinningBid" boolean NOT NULL DEFAULT false, "accountingJournalId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7950d066d322aab3a488ac39fe5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_800d17e11378d42f836d28de0b" ON "bids" ("productId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe34abd3aeb153efaea7a03c67" ON "bids" ("bidderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed46f16a2ffae8257bf8524956" ON "bids" ("productId") `);
        await queryRunner.query(`CREATE TABLE "llm_models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "modelId" character varying NOT NULL, "displayName" character varying NOT NULL, "capabilities" text, "contextWindow" integer NOT NULL DEFAULT '4096', "maxOutputTokens" integer NOT NULL DEFAULT '2048', "inputPricePerMillion" numeric(10,6) NOT NULL DEFAULT '0', "outputPricePerMillion" numeric(10,6) NOT NULL DEFAULT '0', "defaultTemperature" numeric(6,3) NOT NULL DEFAULT '0.7', "isActive" boolean NOT NULL DEFAULT true, "providerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_315c88e45d5dec7ededa8b05507" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."llm_providers_tier_enum" AS ENUM('production', 'development', 'testing')`);
        await queryRunner.query(`CREATE TYPE "public"."llm_providers_providertype_enum" AS ENUM('openai', 'anthropic', 'gemini')`);
        await queryRunner.query(`CREATE TYPE "public"."llm_providers_status_enum" AS ENUM('unknown', 'healthy', 'degraded', 'down')`);
        await queryRunner.query(`CREATE TABLE "llm_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "displayName" character varying NOT NULL, "baseUrl" character varying NOT NULL, "apiKey" character varying NOT NULL, "headers" jsonb, "isActive" boolean NOT NULL DEFAULT true, "tier" "public"."llm_providers_tier_enum" NOT NULL DEFAULT 'production', "providerType" "public"."llm_providers_providertype_enum" NOT NULL DEFAULT 'openai', "status" "public"."llm_providers_status_enum" NOT NULL DEFAULT 'unknown', "lastCheckedAt" TIMESTAMP WITH TIME ZONE, "lastLatencyMs" integer, "consecutiveFailures" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ffeba8a7b7ae85e8c1a76f7440a" UNIQUE ("name"), CONSTRAINT "PK_98a22bf2f8befea87081c600b3f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_usage_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "featureKey" character varying NOT NULL, "modelId" character varying, "providerName" character varying, "userId" character varying, "promptTokens" integer NOT NULL DEFAULT '0', "completionTokens" integer NOT NULL DEFAULT '0', "estimatedCost" numeric(12,6) NOT NULL DEFAULT '0', "latencyMs" integer NOT NULL DEFAULT '0', "success" boolean NOT NULL DEFAULT true, "errorMessage" character varying, "attemptNumber" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f42670987a1de5cb209a77e925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37bb9fd3f1258c105c34b01fe2" ON "ai_usage_logs" ("providerName") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b7df2f119febe42681608800f" ON "ai_usage_logs" ("featureKey", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_87f5cddbcd402ecfff2cc6bc2f" ON "ai_usage_logs" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_feature_configs_quality_enum" AS ENUM('premium', 'standard', 'draft')`);
        await queryRunner.query(`CREATE TABLE "ai_feature_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "featureKey" character varying NOT NULL, "section" character varying NOT NULL, "displayName" character varying NOT NULL, "description" text, "isEnabled" boolean NOT NULL DEFAULT false, "quality" "public"."ai_feature_configs_quality_enum" NOT NULL DEFAULT 'standard', "systemPrompt" text, "temperature" numeric(4,2) NOT NULL DEFAULT '0.7', "maxTokens" integer NOT NULL DEFAULT '2048', "rateLimitPerMinute" integer NOT NULL DEFAULT '10', "rateLimitPerDay" integer NOT NULL DEFAULT '1000', "primaryModelId" uuid, "fallbackModelId" uuid, "tertiaryModelId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0eeea3468f292a582bf494ad059" UNIQUE ("featureKey"), CONSTRAINT "PK_a698c31166b13c89bbe8367e61e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."agent_workflows_trigger_enum" AS ENUM('manual', 'event', 'cron', 'api')`);
        await queryRunner.query(`CREATE TYPE "public"."agent_workflows_status_enum" AS ENUM('active', 'inactive', 'running', 'failed')`);
        await queryRunner.query(`CREATE TABLE "agent_workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "displayName" character varying NOT NULL, "description" text, "trigger" "public"."agent_workflows_trigger_enum" NOT NULL DEFAULT 'manual', "triggerEvent" character varying, "cronExpression" character varying, "steps" jsonb NOT NULL, "isEnabled" boolean NOT NULL DEFAULT true, "status" "public"."agent_workflows_status_enum" NOT NULL DEFAULT 'inactive', "totalRuns" integer NOT NULL DEFAULT '0', "lastRunAt" TIMESTAMP, "lastError" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_207392a92f5948a45392ca2c4e7" UNIQUE ("name"), CONSTRAINT "PK_76cc33610698dc1e9c50487c74c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agent_tools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "displayName" character varying NOT NULL, "description" text, "category" character varying NOT NULL, "endpoint" character varying NOT NULL, "httpMethod" character varying NOT NULL DEFAULT 'GET', "inputSchema" jsonb, "outputSchema" jsonb, "headers" jsonb, "examples" jsonb, "isEnabled" boolean NOT NULL DEFAULT true, "requiresAuth" boolean NOT NULL DEFAULT false, "timeoutMs" integer NOT NULL DEFAULT '15000', "totalCalls" bigint NOT NULL DEFAULT '0', "successRate" numeric(6,2) NOT NULL DEFAULT '100', "lastCalledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5894044efa2b4d7bea5c2cecba3" UNIQUE ("name"), CONSTRAINT "PK_950db085e94f8d3fd8b9728d62b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agent_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agentId" character varying NOT NULL, "agentName" character varying NOT NULL, "eventType" character varying NOT NULL, "payload" jsonb, "latencyMs" numeric(10,2) NOT NULL, "success" boolean NOT NULL, "errorMessage" text, "costEstimate" numeric(12,6) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bacac16f2d0c796a41cf4d0cee5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."agent_instances_category_enum" AS ENUM('marketing', 'security', 'sales', 'support', 'crm', 'operations', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."agent_instances_status_enum" AS ENUM('active', 'inactive', 'degraded', 'learning', 'error')`);
        await queryRunner.query(`CREATE TABLE "agent_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "displayName" character varying NOT NULL, "category" "public"."agent_instances_category_enum" NOT NULL DEFAULT 'custom', "description" text, "systemPrompt" text, "modelId" character varying NOT NULL DEFAULT 'gpt-4o-mini', "providerName" character varying NOT NULL DEFAULT 'openai', "temperature" numeric(4,2) NOT NULL DEFAULT '0.7', "maxTokens" integer NOT NULL DEFAULT '2048', "toolIds" text, "triggerEvents" text, "isEnabled" boolean NOT NULL DEFAULT true, "status" "public"."agent_instances_status_enum" NOT NULL DEFAULT 'inactive', "config" jsonb, "mcpEndpoint" text, "timeoutMs" integer NOT NULL DEFAULT '60000', "maxRetries" integer NOT NULL DEFAULT '3', "totalExecutions" bigint NOT NULL DEFAULT '0', "successRate" numeric(6,2) NOT NULL DEFAULT '0', "avgLatencyMs" numeric(10,2) NOT NULL DEFAULT '0', "lastRunAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d0739d044ef28077ba02280361d" UNIQUE ("name"), CONSTRAINT "PK_70016f72258eafff5d06fdaffb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."advisors_type_enum" AS ENUM('advisor', 'dealer', 'branch')`);
        await queryRunner.query(`CREATE TABLE "advisors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(160) NOT NULL, "type" "public"."advisors_type_enum" NOT NULL DEFAULT 'advisor', "specialty" character varying(120), "description" text, "city" character varying(120) NOT NULL, "region" character varying(120), "country" character varying(100) NOT NULL DEFAULT 'Nigeria', "latitude" numeric(9,6), "longitude" numeric(9,6), "phone" character varying(30), "email" character varying(160), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4baf808487b3dcc389087c9cdeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_188dc53319ef857adf90806b35" ON "advisors" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_07cc40e09698491b91ddf4eaff" ON "advisors" ("country", "region") `);
        await queryRunner.query(`CREATE TYPE "public"."admins_role_enum" AS ENUM('super_admin', 'platform_admin', 'support_admin', 'finance_admin')`);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "name" character varying NOT NULL, "role" "public"."admins_role_enum" NOT NULL DEFAULT 'platform_admin', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_051db7d37d478a69a7432df1479" UNIQUE ("email"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "seller_statistics" ADD CONSTRAINT "FK_e27e0058b3d3628b12aad5cbdef" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_reviews" ADD CONSTRAINT "FK_1160ad4ed6fefbc03da0d96f4dd" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_payouts" ADD CONSTRAINT "FK_1004f82be695e7a05ff0a724aec" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seller_documents" ADD CONSTRAINT "FK_f4e613c1ed4b182686976022f1f" FOREIGN KEY ("seller_id") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_cc2c35974ea67e8d023916abb50" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_participants" ADD CONSTRAINT "FK_e5a9c5cf868f51dabb972930d41" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_participants" ADD CONSTRAINT "FK_2fffd7766a5c57a31e8e81c1b40" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6" FOREIGN KEY ("sellerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_ed46f16a2ffae8257bf85249562" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_5441da18cf4dad4459f0d1d1934" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bids" ADD CONSTRAINT "FK_fe34abd3aeb153efaea7a03c676" FOREIGN KEY ("bidderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "llm_models" ADD CONSTRAINT "FK_e67861ec05270eb1b617068560e" FOREIGN KEY ("providerId") REFERENCES "llm_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" ADD CONSTRAINT "FK_b58384f7bd4e700cb8ec447a027" FOREIGN KEY ("primaryModelId") REFERENCES "llm_models"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" ADD CONSTRAINT "FK_8505dfa33a5f0eb742f6faca54a" FOREIGN KEY ("fallbackModelId") REFERENCES "llm_models"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" ADD CONSTRAINT "FK_bcb5d664331537a50a2a972521f" FOREIGN KEY ("tertiaryModelId") REFERENCES "llm_models"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" DROP CONSTRAINT "FK_bcb5d664331537a50a2a972521f"`);
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" DROP CONSTRAINT "FK_8505dfa33a5f0eb742f6faca54a"`);
        await queryRunner.query(`ALTER TABLE "ai_feature_configs" DROP CONSTRAINT "FK_b58384f7bd4e700cb8ec447a027"`);
        await queryRunner.query(`ALTER TABLE "llm_models" DROP CONSTRAINT "FK_e67861ec05270eb1b617068560e"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_fe34abd3aeb153efaea7a03c676"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_5441da18cf4dad4459f0d1d1934"`);
        await queryRunner.query(`ALTER TABLE "bids" DROP CONSTRAINT "FK_ed46f16a2ffae8257bf85249562"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6"`);
        await queryRunner.query(`ALTER TABLE "room_participants" DROP CONSTRAINT "FK_2fffd7766a5c57a31e8e81c1b40"`);
        await queryRunner.query(`ALTER TABLE "room_participants" DROP CONSTRAINT "FK_e5a9c5cf868f51dabb972930d41"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_cc2c35974ea67e8d023916abb50"`);
        await queryRunner.query(`ALTER TABLE "seller_documents" DROP CONSTRAINT "FK_f4e613c1ed4b182686976022f1f"`);
        await queryRunner.query(`ALTER TABLE "seller_payouts" DROP CONSTRAINT "FK_1004f82be695e7a05ff0a724aec"`);
        await queryRunner.query(`ALTER TABLE "seller_reviews" DROP CONSTRAINT "FK_1160ad4ed6fefbc03da0d96f4dd"`);
        await queryRunner.query(`ALTER TABLE "seller_statistics" DROP CONSTRAINT "FK_e27e0058b3d3628b12aad5cbdef"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TYPE "public"."admins_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07cc40e09698491b91ddf4eaff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_188dc53319ef857adf90806b35"`);
        await queryRunner.query(`DROP TABLE "advisors"`);
        await queryRunner.query(`DROP TYPE "public"."advisors_type_enum"`);
        await queryRunner.query(`DROP TABLE "agent_instances"`);
        await queryRunner.query(`DROP TYPE "public"."agent_instances_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."agent_instances_category_enum"`);
        await queryRunner.query(`DROP TABLE "agent_metrics"`);
        await queryRunner.query(`DROP TABLE "agent_tools"`);
        await queryRunner.query(`DROP TABLE "agent_workflows"`);
        await queryRunner.query(`DROP TYPE "public"."agent_workflows_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."agent_workflows_trigger_enum"`);
        await queryRunner.query(`DROP TABLE "ai_feature_configs"`);
        await queryRunner.query(`DROP TYPE "public"."ai_feature_configs_quality_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87f5cddbcd402ecfff2cc6bc2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b7df2f119febe42681608800f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37bb9fd3f1258c105c34b01fe2"`);
        await queryRunner.query(`DROP TABLE "ai_usage_logs"`);
        await queryRunner.query(`DROP TABLE "llm_providers"`);
        await queryRunner.query(`DROP TYPE "public"."llm_providers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."llm_providers_providertype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."llm_providers_tier_enum"`);
        await queryRunner.query(`DROP TABLE "llm_models"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed46f16a2ffae8257bf8524956"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe34abd3aeb153efaea7a03c67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_800d17e11378d42f836d28de0b"`);
        await queryRunner.query(`DROP TABLE "bids"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77879ae87bfd6ec2b09f1aef64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86e3711405e44c3cb75fbe4c32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a81c6970787322a7763800ffe1"`);
        await queryRunner.query(`DROP TABLE "escrow_holds"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_holds_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_866ddee0e17d9385b4e3b86851"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d35cb3c13a18e1ea1705b2817b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43d19956aeab008b49e0804c14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d07ab3951e510598b2a33290b"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e40a1dd2909378f0da1f34f7bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af69252f6f711708061c2d67f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3932231d2385ac248d0888d95"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_auctiontype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_reservepricevisibility_enum"`);
        await queryRunner.query(`DROP TABLE "room_participants"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4e613c1ed4b182686976022f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0275e551cf97a66c7fc9df2ac1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0822da92cfab6049571426539b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_711765a507b3e11353745309a8"`);
        await queryRunner.query(`DROP TABLE "seller_documents"`);
        await queryRunner.query(`DROP TYPE "public"."seller_documents_verification_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."seller_documents_document_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1004f82be695e7a05ff0a724ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e60c9e914a268fefc1d40edd2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d33a9646fe5fffbd65055a47a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4faef7f35507187503a365f9fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e683c4b40a92ebcf90e894f599"`);
        await queryRunner.query(`DROP TABLE "seller_payouts"`);
        await queryRunner.query(`DROP TYPE "public"."seller_payouts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1160ad4ed6fefbc03da0d96f4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a327b87e879deeadf064c2ce99"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_961760d26e5cccaaa753d6daaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47d6ba0d5ed0edd86295d962d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7a1090232cea58e1d2cbc22f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9feefbe3bab5ddafe2c685fc5"`);
        await queryRunner.query(`DROP TABLE "seller_reviews"`);
        await queryRunner.query(`DROP TYPE "public"."seller_reviews_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e27e0058b3d3628b12aad5cbde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f78e8d7896f293e9f081811f40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87741141abf4b31b06b7f15f7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d23c88ea30e4525411813eb90c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26466f0d02b49c72242fb490db"`);
        await queryRunner.query(`DROP TABLE "seller_statistics"`);
        await queryRunner.query(`DROP TYPE "public"."seller_statistics_period_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c936a07d35e828e7248623242a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a19baf6dd62cac42fbb40a518"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60a049dd3231ed458dccfdaf40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_83f4670f0e114d0be3731bade8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073d5e6499b5a24cd876f7c7d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b99cb17a41a10ffa3d4d0481d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0114dd18eecf7423de5c079b04"`);
        await queryRunner.query(`DROP TABLE "sellers"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_payout_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_verification_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_auction_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_business_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f522735551c716dc489635b5b"`);
        await queryRunner.query(`DROP TABLE "shipping_addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afd0ea7f2d5c017432412f0f29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68c7053f31a2c7f96957097320"`);
        await queryRunner.query(`DROP TABLE "condition_reports"`);
        await queryRunner.query(`DROP TYPE "public"."condition_reports_grade_enum"`);
        await queryRunner.query(`DROP TYPE "public"."condition_reports_condition_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5dc503fab3480182bf436685c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b266f01ca1d077e7ff24c7f67a"`);
        await queryRunner.query(`DROP TABLE "dispute_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf9289f2af9e6714ded345d513"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ea46f4f2225f38d127063c367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4decac99e117c3d35e57f2c1fc"`);
        await queryRunner.query(`DROP TABLE "disputes"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."disputes_reason_enum"`);
        await queryRunner.query(`DROP TABLE "content_pages"`);
        await queryRunner.query(`DROP TABLE "banners"`);
        await queryRunner.query(`DROP TABLE "exchange_rates"`);
        await queryRunner.query(`DROP TABLE "faqs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a09e22b97a449f71089f32cfd"`);
        await queryRunner.query(`DROP TABLE "fee_configs"`);
        await queryRunner.query(`DROP TABLE "invites"`);
        await queryRunner.query(`DROP TYPE "public"."invites_response_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invites_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invites_expiry_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8efb05dbd2ceb9ab8e37c446d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44bb811de7d3cef32f28094ea1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e0c335d17e13b29ffabb74fa7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8506594bec20d9388d86bdf9c0"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e8eebc384627fb6fa7fd3993f"`);
        await queryRunner.query(`DROP TABLE "email_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."email_subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a94d9d61a2b05123710b325fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b3d5cb7b4480ca1c3c367ebb4"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
    }

}
