import { test as setup, expect } from '@playwright/test';
import { existsSync } from 'fs';

// Session for auth'd specs. The state file is (re)generated by
// `node scripts/_make-auth.js` (or a previous setup run); when it already
// exists we reuse it to keep runs fast and deterministic.
const authFile = 'playwright/.auth/admin.json';

setup('ensure admin session', async () => {
  expect(existsSync(authFile), authFile + ' missing — run `node scripts/_make-auth.js` once').toBe(true);
});