import { test as setup, expect } from '@playwright/test';
import { existsSync } from 'fs';

// Sessions for auth'd specs.
// - admin: state file is (re)generated by `node scripts/_make-auth.js` (or a
//   previous setup run); when it already exists we reuse it to keep runs fast.
// - seller/buyer: minted here on every setup pass via the UI login flow
//   (same approach as _make-auth.js), covering the demo seller/buyer accounts.
const adminFile = 'playwright/.auth/admin.json';
const sellerFile = 'playwright/.auth/seller.json';
const buyerFile = 'playwright/.auth/buyer.json';

async function uiLogin(
  page: import('@playwright/test').Page,
  email: string,
  password: string,
  dashboardUrl: RegExp,
) {
  await page.goto('/en/auth/login', { waitUntil: 'domcontentloaded' });
  // Setup tests run with the public storageState (cookie consent pre-accepted),
  // so the banner may not render at all — never let this click eat the budget.
  await page.getByRole('button', { name: /accept all/i }).click({ timeout: 2_500 }).catch(() => {});
  await page.getByLabel('Email').fill(email);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: /sign in/i }).click();
  await page.waitForURL(dashboardUrl, { timeout: 60_000 });
}

setup.setTimeout(120_000);

setup('ensure admin session', async () => {
  expect(existsSync(adminFile), adminFile + ' missing — run `node scripts/_make-auth.js` once').toBe(true);
});

setup('mint seller session', async ({ page }) => {
  await uiLogin(page, 'demo@seller.com', 'Seller@12345', /seller\/dashboard/);
  await page.waitForLoadState('domcontentloaded');
  await page.context().storageState({ path: sellerFile });
});

setup('mint buyer session', async ({ page }) => {
  await uiLogin(page, 'demo@buyer.com', 'Buyer@12345', /buyer\/dashboard/);
  await page.waitForLoadState('domcontentloaded');
  await page.context().storageState({ path: buyerFile });
});
